
package gymmanagementsystem;

import Backend.Dates;
import Backend.Scaling;
import Backend.managementclasses.Admin;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

public class MainPage extends javax.swing.JFrame {

    
    private ImageIcon addMemberImage = new ImageIcon("");
    private Admin admin;
    
    public MainPage(Admin admin) {
        this.admin=admin;
        initComponents();
        initOtherComponents();
    }
    
    private void initOtherComponents(){
        // aligning texts center
        textCurrentDate.setText(Dates.getCurrentDate());
        textUsername.setText(admin.getName());
   
    }
    
    
    
     private void close() {
        WindowEvent windowClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JToggleButton();
        textCurrentDate = new javax.swing.JLabel();
        textDeleteMember3 = new javax.swing.JLabel();
        textShowAllDeleted = new javax.swing.JLabel();
        textShowAllMembers = new javax.swing.JLabel();
        textShowAll = new javax.swing.JLabel();
        textDeleteMember1 = new javax.swing.JLabel();
        textUpdate = new javax.swing.JLabel();
        textDeleteMember = new javax.swing.JLabel();
        textDelete = new javax.swing.JLabel();
        textAdd = new javax.swing.JLabel();
        textUsername = new javax.swing.JLabel();
        textProfile = new javax.swing.JLabel();
        textAddMember = new javax.swing.JLabel();
        textBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(51, 51, 51));
        btnLogOut.setText("Log out");
        btnLogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 610, 120, 50));

        textCurrentDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textCurrentDate.setForeground(new java.awt.Color(255, 255, 255));
        textCurrentDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textCurrentDate.setText("Harry Yo");
        jPanel1.add(textCurrentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 200, -1));

        textDeleteMember3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ShowAllMembersLogo.png"))); // NOI18N
        textDeleteMember3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textDeleteMember3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textDeleteMember3MouseClicked(evt);
            }
        });
        jPanel1.add(textDeleteMember3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 110, 110));

        textShowAllDeleted.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textShowAllDeleted.setForeground(new java.awt.Color(255, 255, 255));
        textShowAllDeleted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textShowAllDeleted.setText("Show All Deleted");
        jPanel1.add(textShowAllDeleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 300, 110, 20));

        textShowAllMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ShowAllMembersLogo.png"))); // NOI18N
        textShowAllMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textShowAllMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textShowAllMembersMouseClicked(evt);
            }
        });
        jPanel1.add(textShowAllMembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 110, 110));

        textShowAll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textShowAll.setForeground(new java.awt.Color(255, 255, 255));
        textShowAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textShowAll.setText("Show All Members");
        jPanel1.add(textShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 110, 20));

        textDeleteMember1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDeleteMember1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditMemberLogo.png"))); // NOI18N
        textDeleteMember1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textDeleteMember1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textDeleteMember1MouseClicked(evt);
            }
        });
        jPanel1.add(textDeleteMember1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 110, 110));

        textUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textUpdate.setForeground(new java.awt.Color(255, 255, 255));
        textUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textUpdate.setText("Update Member");
        jPanel1.add(textUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 110, 20));

        textDeleteMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeleteMemberLogo.png"))); // NOI18N
        textDeleteMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textDeleteMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textDeleteMemberMouseClicked(evt);
            }
        });
        jPanel1.add(textDeleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, 110));

        textDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textDelete.setForeground(new java.awt.Color(255, 255, 255));
        textDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDelete.setText("Delete Member");
        jPanel1.add(textDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 110, 20));

        textAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textAdd.setForeground(new java.awt.Color(255, 255, 255));
        textAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textAdd.setText("Add Member");
        jPanel1.add(textAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 110, 20));

        textUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textUsername.setForeground(new java.awt.Color(255, 255, 255));
        textUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textUsername.setText("Harry Yo");
        jPanel1.add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 200, -1));

        textProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GymLogo.png"))); // NOI18N
        jPanel1.add(textProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -50, 230, 230));

        textAddMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddMemberLogo.png"))); // NOI18N
        textAddMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textAddMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textAddMemberMouseClicked(evt);
            }
        });
        jPanel1.add(textAddMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, 110));

        textBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MainPageBackground.png"))); // NOI18N
        textBackground.setText("  ");
        jPanel1.add(textBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textAddMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAddMemberMouseClicked
       close();
       new AddMemberForm(admin).setVisible(true);
    }//GEN-LAST:event_textAddMemberMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        close();
        new AdminLoginGUI().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void textDeleteMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDeleteMemberMouseClicked
       close();
       new DeleteMember(admin).setVisible(true);
    }//GEN-LAST:event_textDeleteMemberMouseClicked

    private void textDeleteMember1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDeleteMember1MouseClicked
       close();
       new UpdateMemberForm(admin).setVisible(true);
    }//GEN-LAST:event_textDeleteMember1MouseClicked

    private void textShowAllMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textShowAllMembersMouseClicked
      close();
      new ShowAllMembersForm(admin).setVisible(true);
    }//GEN-LAST:event_textShowAllMembersMouseClicked

    private void textDeleteMember3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDeleteMember3MouseClicked
       close();
      new ShowAllDeletedMembersForm(admin).setVisible(true);
    }//GEN-LAST:event_textDeleteMember3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage(new Admin("Name","Email","Password")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLogOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textAdd;
    private javax.swing.JLabel textAddMember;
    private javax.swing.JLabel textBackground;
    private javax.swing.JLabel textCurrentDate;
    private javax.swing.JLabel textDelete;
    private javax.swing.JLabel textDeleteMember;
    private javax.swing.JLabel textDeleteMember1;
    private javax.swing.JLabel textDeleteMember3;
    private javax.swing.JLabel textProfile;
    private javax.swing.JLabel textShowAll;
    private javax.swing.JLabel textShowAllDeleted;
    private javax.swing.JLabel textShowAllMembers;
    private javax.swing.JLabel textUpdate;
    private javax.swing.JLabel textUsername;
    // End of variables declaration//GEN-END:variables
}
